# frozen_string_literal: true

header = ARGV[0] || "/usr/include/linux/input-event-codes.h"
out_path = ARGV[1] || File.expand_path("../src/keycodes.rb", __dir__)

values = {}
records = []

File.readlines(header).each do |line|
  next unless line =~ /^\s*#define\s+((?:KEY|BTN)_[A-Z0-9_]+)\s+(.+?)(?:\s+\/\*.*)?$/

  name = Regexp.last_match(1)
  expr = Regexp.last_match(2).strip
  next if name.end_with?("_CNT")

  value = if expr.match?(/\A0x[0-9a-fA-F]+\z/)
    expr.to_i(16)
  elsif expr.match?(/\A\d+\z/)
    expr.to_i
  elsif expr =~ /\A([A-Z0-9_]+)\z/
    values[Regexp.last_match(1)]
  elsif expr =~ /\A\(([A-Z0-9_]+)\s*\+\s*(\d+)\)\z/
    base = values[Regexp.last_match(1)]
    base && base + Regexp.last_match(2).to_i
  end

  next if value.nil?

  values[name] = value
  records << [name, value]
end

range_aliases = %w[
  BTN_MISC BTN_MOUSE BTN_JOYSTICK BTN_GAMEPAD BTN_DIGI BTN_WHEEL BTN_TRIGGER_HAPPY
  KEY_MIN_INTERESTING KEY_MAX
]

public_records = records
  .reject { |name, _value| name.end_with?("_CNT") || range_aliases.include?(name) }
  .map do |name, value|
    public_name = name.start_with?("KEY_") ? name.delete_prefix("KEY_") : name
    [value, public_name]
  end

key_name_by_code = {}
public_records.each { |value, name| key_name_by_code[value] = name }

key_pairs = key_name_by_code.sort_by(&:first)
code_pairs = public_records.map { |value, name| [name, value] }.uniq.sort_by(&:first)
key_codes = public_records.map(&:first).uniq.sort

File.open(out_path, "w") do |f|
  f.puts "# frozen_string_literal: true"
  f.puts
  f.puts "# Generated by native/tools/gen_keycodes.rb from #{header}."
  f.puts "module Keycodes"
  f.puts "  KEYMAP = {"
  key_pairs.each do |value, name|
    f.puts "    #{value} => #{name.inspect},"
  end
  f.puts "  }.freeze"
  f.puts
  f.puts "  CODEMAP = {"
  code_pairs.each do |name, value|
    f.puts "    #{name.inspect} => #{value},"
  end
  f.puts "  }.freeze"
  f.puts
  f.puts "  KEY_CODES = ["
  key_codes.each_slice(12) do |slice|
    f.puts "    #{slice.join(", ")},"
  end
  f.puts "  ].freeze"
  f.puts "end"
end
