#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "../lib/fusuma/plugin/remap/version"
require_relative "../lib/fusuma/plugin/remap/remapper"
require_relative "../lib/fusuma/plugin/remap/layer_manager"
require "fusuma/config"
require "revdev"
require "msgpack"

include Revdev

if ARGV.length > 1
  source_keyboards = [Revdev::EventDevice.new(ARGV.shift)]
  internal_touchpad = Revdev::EventDevice.new(ARGV.shift)
else
  warn "Usage: #{$PROGRAM_NAME} /dev/input/KEYBOARD /dev/input/TOUCHPAD"
  exit false
end

Fusuma::Config.instance.custom_path = "~/.config/fusuma/config.yml"

layer_manager = Fusuma::Plugin::Remap::LayerManager.instance

keyboard_reader, keyboard_writer = IO.pipe
Thread.new do
  layer_manager.send_layer(layer: { foo: 'bar' })
  sleep 3
  layer_manager.send_layer(layer: { thumbsense: true })
  sleep 3
  layer_manager.send_layer(layer: { thumbsense: true }, remove: true)

  # u = MessagePack::Unpacker.new(keyboard_reader)
  # loop do
  #   puts "unpack: #{u.unpack}"
  # end
end


Fusuma::Plugin::Remap::Remapper.new(
  layer_manager: layer_manager,
  keyboard_writer: keyboard_writer,
  source_keyboards: source_keyboards,
  internal_touchpad: internal_touchpad
).run
